### Calculations of $\epsilon _{Nd}$

$$\epsilon _{Nd} = \left(\frac{(\frac{^{143}Nd}{^{144}Nd})_i^{sample}}{(\frac{^{143}Nd}{^{144}Nd})_i^{CHUR}} -1\right)\times 10^4$$

where :

* $(\frac{^{143}Nd}{^{144}Nd})_t = (\frac{^{143}Nd}{^{144}Nd})_0 - (\frac{^{147}Sm}{^{144}Nd})_0(e^{\lambda t}-1)$ : we need to determine this ratio for both sample and CHUR at time t


* $\lambda_{147_{Sm}} = 6.54\times 10^{-12}y^{-1}$ (Lugmair and Marti 1978)


* $\frac{^{147}Sm}{^{144}Nd} = (\frac{C_{Sm}}{C_{Nd}})\left[0.53151 + 0.14252 \frac{^{143}Nd}{^{144}Nd}  \right]$


* $^{143}Nd/^{144}Nd_{CHUR} = 0.512638$ and $^{147}Sm/^{144}Nd_{CHUR} = 0.1967$ (Jacobsen and Wasserburg 1980)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("olondo_sm_nd.csv")
df.head()

,Roch type,Sample,Age,Sm,Nd,147Sm/144Nd,143Nd/144Nd,Err,eNd(0),eNd(t)
0,Komatiitic basalt,OL1601,3000,1.99,5.78,0.2069,0.51294,6,5.8,1.89
1,Komatiitic basalt,OL1602,3000,2.08,6.19,0.2017,0.51284,8,3.9,1.99
2,Komatiitic basalt,OL16100,3000,1.97,6.18,0.1911,0.51262,5,-0.4,1.74
3,Komatiitic basalt,O-1-1,3000,1.88,5.73,0.1988,0.51283,6,3.7,2.89
4,Komatiitic basalt,O-1-2,3000,2.06,6.44,0.1937,0.51268,4,0.8,2.00

In [35]:
df["147Sm/144Nd_re"] = df["Sm"]/df["Nd"]*(0.53151+0.14252*df["143Nd/144Nd"])
Nd143_Nd144CHUR = 0.512638
Sm147_Nd144CHUR = 0.1967
lda = 6.54e-12
df["eNd(0)_re"] = (df["143Nd/144Nd"]/Nd143_Nd144CHUR-1) * 10**4
df["eNd(0)_re"] = df["eNd(0)_re"].round(1)
df["143Nd/144Ndt"] = df["143Nd/144Nd"] - df["147Sm/144Nd_re"]*(np.exp(lda*df["Age"]*10**6)-1)
df["143Nd/144Nd_CHURt"] = Nd143_Nd144CHUR - Sm147_Nd144CHUR*(np.exp(lda*df["Age"]*10**6)-1)
df["eNd(t)_re"] = (df["143Nd/144Ndt"]/df["143Nd/144Nd_CHURt"]-1) * 10**4
df["eNd(t)_re"] = df["eNd(t)_re"].round(2)

In [36]:
df.iloc[:,[0,1,3,4,10,6,8,11,9,14]]

,Roch type,Sample,Sm,Nd,147Sm/144Nd_re,143Nd/144Nd,eNd(0),eNd(0)_re,eNd(t),eNd(t)_re
0,Komatiitic basalt,OL1601,1.99,5.78,0.208163,0.51294,5.8,5.9,1.89,1.47
1,Komatiitic basalt,OL1602,2.08,6.19,0.203161,0.51284,3.9,3.9,1.99,1.45
2,Komatiitic basalt,OL16100,1.97,6.18,0.192718,0.51262,-0.4,-0.4,1.74,1.20
3,Komatiitic basalt,O-1-1,1.88,5.73,0.198367,0.51283,3.7,3.7,2.89,3.12
4,Komatiitic basalt,O-1-2,2.06,6.44,0.193390,0.51268,0.8,0.8,2.00,2.11
5,Tholeiitic basalts,OL1604,2.87,8.27,0.209824,0.51294,5.8,5.9,1.19,0.82
6,Tholeiitic basalts,OL1606,1.59,4.06,0.236813,0.51348,16.4,16.4,1.35,0.93
7,Tholeiitic basalts,OL1607,1.63,4.23,0.233010,0.51341,15.0,15.1,1.89,1.03
8,Tholeiitic basalts,OL1610,1.60,5.61,0.172410,0.51223,-8.0,-8.0,1.85,1.44
9,Tholeiitic basalts,OL1612,1.67,5.90,0.171109,0.51225,-7.6,-7.6,2.68,2.34
10,Tholeiitic basalts,OL1613,1.55,5.48,0.170986,0.51226,-7.4,-7.4,2.92,2.58
11,Tholeiitic basalts,OL1614,0.85,2.58,0.199182,0.51268,0.8,0.8,0.53,-0.14
12,Tholeiitic basalts,OL1615,2.02,6.41,0.190523,0.51270,1.1,1.2,3.98,3.62
13,Tholeiitic basalts,OL1616,2.08,6.12,0.205484,0.51282,3.6,3.6,0.59,0.16
14,Tholeiitic basalts,OL1617,1.99,5.92,0.203234,0.51281,3.4,3.4,1.62,0.84
15,Tholeiitic basalts,OL1621,3.10,9.04,0.207335,0.51295,6.0,6.1,2.61,1.99
16,Tholeiitic basalts,OL1623,1.76,5.28,0.201536,0.51290,5.1,5.1,3.85,3.27
17,Tholeiitic basalts,OL1624,1.77,6.26,0.170924,0.51222,-8.2,-8.2,2.26,1.82
18,Tholeiitic basalts,OL1650,1.92,5.94,0.195423,0.51278,2.7,2.8,3.59,3.29
19,Tholeiitic basalts,OL1651,2.18,6.02,0.218952,0.51304,7.9,7.8,0.02,-0.76
20,Tholeiitic basalts,O-1-1,1.88,5.73,0.198367,0.51283,3.7,3.7,2.89,3.12
21,Tholeiitic basalts,O-10,1.60,4.73,0.204518,0.51288,4.8,4.7,1.81,1.71
22,Tholeiitic basalts,O-11-3,1.52,5.10,0.180178,0.51246,-3.5,-3.5,3.05,2.94
23,Tholeiitic basalts,O-19-1,2.16,6.40,0.204057,0.51294,5.8,5.9,2.89,3.07
24,Tholeiitic basalts,O-2,2.81,8.23,0.206434,0.51291,5.3,5.3,1.52,1.56
25,Tholeiitic basalts,O-4,1.79,4.76,0.227390,0.51340,14.8,14.9,2.92,3.03